#!/usr/bin/env bash

REPO_DIR=$(dirname "$(readlink -f "${0}")")

@goal default
@depends_on test

@goal test
@depends_on _tush_downloaded
    cd test || exit 1
    PATH="${REPO_DIR}/test/tush/bin:${PATH}" \
        tush-check ./*.tush

@goal clean
    rm --recursive --force test/tush

@goal _tush_downloaded
@reached_if [ -d test/tush/.git ]
    cd test || exit 1
    test ! -d tush || rm --recursive tush
    git clone https://github.com/darius/tush.git
